#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
CHART_DIR="$REPO_ROOT/deploy/helm/pgh-broker"
DOCKERFILE="$REPO_ROOT/Dockerfile.pgh-broker"
ENV_FILE="${PGH_WIZARD_ENV_FILE:-$REPO_ROOT/.env.pgh-deploy}"
WIZARD_TMP_DIR=""
CURRENT_COMMIT=""
DEPLOYMENT_NAME=""
SERVICE_NAME=""
HELM_VALUE_ARGS=()

umask 077
touch "$ENV_FILE"
chmod 600 "$ENV_FILE"

die() {
  printf '  %serror:%s %s\n' "$RED" "$RESET" "$1" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

require_value() {
  [[ -n "$2" ]] || die "$1 is required"
}

validate_dns_label() {
  [[ "$2" =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$ ]] && ((${#2} <= 63)) ||
    die "$1 must be a lowercase Kubernetes DNS label"
}

validate_dns_subdomain() {
  [[ "$2" =~ ^([a-z0-9]([-a-z0-9]*[a-z0-9])?)(\.([a-z0-9]([-a-z0-9]*[a-z0-9])?))*$ ]] &&
    ((${#2} <= 253)) || die "$1 must be a lowercase DNS subdomain"
}

validate_release_name() {
  validate_dns_subdomain "Helm release" "$1"
  ((${#1} <= 53)) || die "Helm release must be at most 53 characters"
}

validate_hostname() {
  validate_dns_subdomain "broker host" "$1"
  [[ "$1" == *.* ]] || die "broker host must contain a DNS suffix"
}

kubectl_cluster() {
  kubectl --context "$KUBE_CONTEXT" "$@"
}

kubectl_ns() {
  kubectl --context "$KUBE_CONTEXT" --namespace "$KUBE_NAMESPACE" "$@"
}

ensure_tmp_dir() {
  if [[ -z "$WIZARD_TMP_DIR" ]]; then
    WIZARD_TMP_DIR=$(mktemp -d "${TMPDIR:-/tmp}/pgh-k8s-wizard.XXXXXXXX")
  fi
}

clear_sensitive_material() {
  unset PGH_DATABASE_URL PGH_ENCRYPTION_KEYS PGH_OPERATOR_PAT CAPABILITY_TOKEN
  if [[ -n "$WIZARD_TMP_DIR" && "$WIZARD_TMP_DIR" == "${TMPDIR:-/tmp}/pgh-k8s-wizard."* ]]; then
    rm -rf -- "$WIZARD_TMP_DIR"
  fi
  WIZARD_TMP_DIR=""
}

cleanup() {
  clear_sensitive_material
}
trap cleanup EXIT
trap 'cleanup; exit 130' INT TERM

validate_grants() {
  local grant
  for grant in "$@"; do
    case "$grant" in
      actions.write|checks.write|contents.write|deployments.write|objects.delete|releases.write) ;;
      *) die "unknown grant: $grant" ;;
    esac
  done
}

banner "pgh Broker Kubernetes deployment"

stage "Preflight"
say "This wizard deploys the Broker from this checkout and pauses before every cluster mutation."
for required in git kubectl helm docker openssl curl; do
  require_command "$required"
done
docker buildx version >/dev/null 2>&1 || die "Docker Buildx is required"
[[ -f "$DOCKERFILE" ]] || die "missing $DOCKERFILE"
[[ -f "$CHART_DIR/Chart.yaml" ]] || die "missing Helm chart at $CHART_DIR"
CURRENT_COMMIT=$(git -C "$REPO_ROOT" rev-parse HEAD)
note "source commit: $CURRENT_COMMIT"
if [[ -n "$(git -C "$REPO_ROOT" status --short --untracked-files=no)" ]]; then
  warn "The checkout has tracked modifications that are not represented by commit $CURRENT_COMMIT."
  confirm "Continue and build those local modifications?" || die "stopped before building"
fi
pause "Preflight passed. Press Enter to select the cluster."

stage "Cluster and namespace"
say "Select the exact kubeconfig context. The context is passed explicitly to every command."
kubectl config get-contexts
CURRENT_CONTEXT=$(kubectl config current-context 2>/dev/null || true)
[[ -n "$(_existing KUBE_CONTEXT || true)" ]] || write_env KUBE_CONTEXT "$CURRENT_CONTEXT"
ask KUBE_CONTEXT "Kubernetes context:"
require_value "Kubernetes context" "$KUBE_CONTEXT"
kubectl config get-contexts "$KUBE_CONTEXT" >/dev/null 2>&1 || die "unknown context: $KUBE_CONTEXT"
[[ -n "$(_existing KUBE_NAMESPACE || true)" ]] || write_env KUBE_NAMESPACE "pgh-system"
ask KUBE_NAMESPACE "Namespace:"
validate_dns_label "namespace" "$KUBE_NAMESPACE"
[[ -n "$(_existing HELM_RELEASE || true)" ]] || write_env HELM_RELEASE "pgh-broker"
ask HELM_RELEASE "Helm release:"
validate_release_name "$HELM_RELEASE"
write_env KUBE_CONTEXT "$KUBE_CONTEXT"
write_env KUBE_NAMESPACE "$KUBE_NAMESPACE"
write_env HELM_RELEASE "$HELM_RELEASE"
kubectl_cluster cluster-info
kubectl_cluster auth can-i create deployments --namespace "$KUBE_NAMESPACE" | grep -qx yes ||
  die "current identity cannot create Deployments in namespace $KUBE_NAMESPACE"
warn "Next action creates or reconciles namespace $KUBE_NAMESPACE in context $KUBE_CONTEXT."
confirm "Apply the namespace now?" || die "stopped before namespace mutation"
kubectl_cluster create namespace "$KUBE_NAMESPACE" --dry-run=client -o yaml |
  kubectl_cluster apply -f -

stage "Build and publish image"
say "Use an immutable image tag. The default is the full source commit."
ask IMAGE_REPOSITORY "Image repository, for example registry.example.com/platform/pgh-broker:"
require_value "image repository" "$IMAGE_REPOSITORY"
[[ "$IMAGE_REPOSITORY" != *[[:space:]]* ]] || die "image repository cannot contain whitespace"
[[ "$IMAGE_REPOSITORY" != *@* ]] || die "enter a repository without a digest"
[[ "${IMAGE_REPOSITORY##*/}" != *:* ]] || die "enter the image repository without a tag"
[[ "$IMAGE_REPOSITORY" != *[,=]* ]] || die "image repository contains an unsupported character"
[[ -n "$(_existing IMAGE_TAG || true)" ]] || write_env IMAGE_TAG "$CURRENT_COMMIT"
ask IMAGE_TAG "Image tag:"
require_value "image tag" "$IMAGE_TAG"
[[ "$IMAGE_TAG" != *[[:space:]/:]* ]] || die "image tag cannot contain whitespace, slash, or colon"
[[ -n "$(_existing IMAGE_PLATFORM || true)" ]] || write_env IMAGE_PLATFORM "linux/amd64"
ask IMAGE_PLATFORM "Target platform:"
require_value "target platform" "$IMAGE_PLATFORM"
ask IMAGE_PULL_SECRET "Existing image pull Secret name (blank if registry is public):"
if [[ -n "$IMAGE_PULL_SECRET" ]]; then
  validate_dns_label "image pull Secret" "$IMAGE_PULL_SECRET"
fi
write_env IMAGE_REPOSITORY "$IMAGE_REPOSITORY"
write_env IMAGE_TAG "$IMAGE_TAG"
write_env IMAGE_PLATFORM "$IMAGE_PLATFORM"
write_env IMAGE_PULL_SECRET "$IMAGE_PULL_SECRET"
IMAGE_REF="$IMAGE_REPOSITORY:$IMAGE_TAG"
if docker buildx imagetools inspect "$IMAGE_REF" >/dev/null 2>&1; then
  warn "Image $IMAGE_REF already exists. Reusing a mutable or unrelated image under this tag is unsafe."
  confirm "Reuse this exact published image?" || die "choose a new image tag and rerun"
else
  warn "Next action builds this checkout and pushes $IMAGE_REF to the configured registry."
  confirm "Build and push the Broker image?" || die "stopped before registry mutation"
  docker buildx build \
    --platform "$IMAGE_PLATFORM" \
    --file "$DOCKERFILE" \
    --tag "$IMAGE_REF" \
    --push \
    "$REPO_ROOT"
fi

stage "Database and encryption Secrets"
say "Use an existing production PostgreSQL service and a keyring from your secret manager."
step "Retrieve the PostgreSQL URL. Input is hidden and is never written to the wizard state file."
ask_secret PGH_DATABASE_URL "PostgreSQL URL:"
require_value "PostgreSQL URL" "$PGH_DATABASE_URL"
[[ "$PGH_DATABASE_URL" == postgres://* || "$PGH_DATABASE_URL" == postgresql://* ]] ||
  die "PostgreSQL URL must use postgres:// or postgresql://"
[[ "$PGH_DATABASE_URL" != *"sslmode=disable"* ]] || die "sslmode=disable is not accepted for this deployment"
if [[ "$PGH_DATABASE_URL" != *"sslmode=require"* &&
      "$PGH_DATABASE_URL" != *"sslmode=verify-ca"* &&
      "$PGH_DATABASE_URL" != *"sslmode=verify-full"* ]]; then
  warn "The URL does not declare sslmode=require, verify-ca, or verify-full."
  confirm "The database connection is otherwise TLS-protected and you want to continue?" ||
    die "stopped before storing the database URL"
fi
[[ -n "$(_existing PGH_ACTIVE_KEY_ID || true)" ]] ||
  write_env PGH_ACTIVE_KEY_ID "key-$(date -u +%Y-%m)"
ask PGH_ACTIVE_KEY_ID "Active encryption key ID:"
validate_dns_label "active encryption key ID" "$PGH_ACTIVE_KEY_ID"
step "Retrieve the complete key-id:base64 keyring. Preserve old keys during rotation."
ask_secret PGH_ENCRYPTION_KEYS "Encryption keyring:"
require_value "encryption keyring" "$PGH_ENCRYPTION_KEYS"
[[ ",$PGH_ENCRYPTION_KEYS," == *",$PGH_ACTIVE_KEY_ID:"* ]] ||
  die "the keyring does not contain active key ID $PGH_ACTIVE_KEY_ID"
write_env PGH_ACTIVE_KEY_ID "$PGH_ACTIVE_KEY_ID"
if kubectl_ns get secret pgh-broker-database >/dev/null 2>&1 ||
   kubectl_ns get secret pgh-broker-encryption >/dev/null 2>&1; then
  warn "One or both Broker Secrets already exist. Applying replaces their managed data keys."
fi
confirm "Create or replace the Broker database and encryption Secrets?" ||
  die "stopped before Secret mutation"
ensure_tmp_dir
printf '%s' "$PGH_DATABASE_URL" > "$WIZARD_TMP_DIR/database-url"
printf '%s' "$PGH_ENCRYPTION_KEYS" > "$WIZARD_TMP_DIR/encryption-keys"
printf '%s' "$PGH_ACTIVE_KEY_ID" > "$WIZARD_TMP_DIR/active-key-id"
kubectl_ns create secret generic pgh-broker-database \
  --from-file=url="$WIZARD_TMP_DIR/database-url" \
  --dry-run=client -o yaml |
  kubectl_ns apply -f -
kubectl_ns create secret generic pgh-broker-encryption \
  --from-file=keys="$WIZARD_TMP_DIR/encryption-keys" \
  --from-file=active-key-id="$WIZARD_TMP_DIR/active-key-id" \
  --dry-run=client -o yaml |
  kubectl_ns apply -f -
DEPLOYMENT_REVISION="$(date -u +%Y%m%dT%H%M%SZ)-$(openssl rand -hex 8)"
write_env PGH_DEPLOYMENT_REVISION "$DEPLOYMENT_REVISION"
clear_sensitive_material

stage "Render and review"
say "Render locally, lint the chart, and show the server-side object diff before deployment."
HELM_VALUE_ARGS=(
  --set-string "image.repository=$IMAGE_REPOSITORY"
  --set-string "image.tag=$IMAGE_TAG"
  --set-string "podAnnotations.pgh\\.github-proxy/deployment-revision=$DEPLOYMENT_REVISION"
)
if [[ -n "$IMAGE_PULL_SECRET" ]]; then
  kubectl_ns get secret "$IMAGE_PULL_SECRET" >/dev/null 2>&1 ||
    die "image pull Secret does not exist: $IMAGE_PULL_SECRET"
  HELM_VALUE_ARGS+=(--set-string "imagePullSecrets[0].name=$IMAGE_PULL_SECRET")
fi
helm lint "$CHART_DIR" "${HELM_VALUE_ARGS[@]}"
ensure_tmp_dir
RENDERED_MANIFEST="$WIZARD_TMP_DIR/rendered.yaml"
helm template "$HELM_RELEASE" "$CHART_DIR" \
  --namespace "$KUBE_NAMESPACE" \
  "${HELM_VALUE_ARGS[@]}" > "$RENDERED_MANIFEST"
if kubectl_ns diff -f "$RENDERED_MANIFEST"; then
  note "No chart-managed object changes detected."
else
  DIFF_STATUS=$?
  [[ "$DIFF_STATUS" -eq 1 ]] || die "kubectl diff failed with status $DIFF_STATUS"
fi
note "context: $KUBE_CONTEXT"
note "namespace: $KUBE_NAMESPACE"
note "release: $HELM_RELEASE"
note "image: $IMAGE_REF"
pause "Review the diff above. Press Enter when ready for the deployment approval."

stage "Deploy Broker"
warn "Next action changes the Helm release and waits atomically for readiness. A failure rolls it back."
confirm "Deploy release $HELM_RELEASE to $KUBE_CONTEXT/$KUBE_NAMESPACE?" ||
  die "stopped before Helm mutation"
helm upgrade --install "$HELM_RELEASE" "$CHART_DIR" \
  --kube-context "$KUBE_CONTEXT" \
  --namespace "$KUBE_NAMESPACE" \
  --atomic \
  --wait \
  --timeout 10m \
  "${HELM_VALUE_ARGS[@]}"
DEPLOYMENT_NAME=$(kubectl_ns get deployment \
  -l "app.kubernetes.io/name=pgh-broker,app.kubernetes.io/instance=$HELM_RELEASE" \
  -o jsonpath='{.items[0].metadata.name}')
SERVICE_NAME=$(kubectl_ns get service \
  -l "app.kubernetes.io/name=pgh-broker,app.kubernetes.io/instance=$HELM_RELEASE" \
  -o jsonpath='{.items[0].metadata.name}')
require_value "rendered Broker Deployment name" "$DEPLOYMENT_NAME"
require_value "rendered Broker Service name" "$SERVICE_NAME"
write_env PGH_DEPLOYMENT_NAME "$DEPLOYMENT_NAME"
write_env PGH_SERVICE_NAME "$SERVICE_NAME"
kubectl_ns rollout status "deployment/$DEPLOYMENT_NAME" --timeout=10m
helm status "$HELM_RELEASE" --kube-context "$KUBE_CONTEXT" --namespace "$KUBE_NAMESPACE"

stage "TLS ingress"
say "Create a standard HTTPS Ingress using an existing controller and TLS Secret."
kubectl_cluster get ingressclass
ask PGH_HOST "Broker hostname, without https://:"
validate_hostname "$PGH_HOST"
ask INGRESS_CLASS "Existing IngressClass name:"
validate_dns_subdomain "IngressClass" "$INGRESS_CLASS"
ask INGRESS_TLS_SECRET "Existing TLS Secret name:"
validate_dns_label "TLS Secret" "$INGRESS_TLS_SECRET"
[[ -n "$(_existing INGRESS_NAME || true)" ]] || write_env INGRESS_NAME "$HELM_RELEASE-pgh"
ask INGRESS_NAME "Ingress object name:"
validate_dns_label "Ingress name" "$INGRESS_NAME"
kubectl_cluster get ingressclass "$INGRESS_CLASS" >/dev/null 2>&1 || die "IngressClass does not exist"
TLS_SECRET_TYPE=$(kubectl_ns get secret "$INGRESS_TLS_SECRET" -o jsonpath='{.type}' 2>/dev/null || true)
[[ "$TLS_SECRET_TYPE" == kubernetes.io/tls ]] || die "TLS Secret is missing or is not kubernetes.io/tls"
write_env PGH_HOST "$PGH_HOST"
write_env INGRESS_CLASS "$INGRESS_CLASS"
write_env INGRESS_TLS_SECRET "$INGRESS_TLS_SECRET"
write_env INGRESS_NAME "$INGRESS_NAME"
ensure_tmp_dir
INGRESS_MANIFEST="$WIZARD_TMP_DIR/ingress.yaml"
cat > "$INGRESS_MANIFEST" <<EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $INGRESS_NAME
  namespace: $KUBE_NAMESPACE
spec:
  ingressClassName: $INGRESS_CLASS
  tls:
    - hosts:
        - $PGH_HOST
      secretName: $INGRESS_TLS_SECRET
  rules:
    - host: $PGH_HOST
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: $SERVICE_NAME
                port:
                  number: 8080
EOF
if kubectl_ns diff -f "$INGRESS_MANIFEST"; then
  note "No Ingress change detected."
else
  DIFF_STATUS=$?
  [[ "$DIFF_STATUS" -eq 1 ]] || die "Ingress diff failed with status $DIFF_STATUS"
fi
warn "Ingress reachability is controlled by your controller and network policy, not by this manifest."
step "Confirm the controller is restricted to approved Agent Hosts before exposing the Broker."
confirm "Apply this HTTPS Ingress?" || die "stopped before Ingress mutation"
kubectl_ns apply -f "$INGRESS_MANIFEST"
HEALTH_READY=false
for _ in 1 2 3 4 5 6; do
  if curl --fail --silent --show-error --max-time 10 "https://$PGH_HOST/healthz" >/dev/null; then
    HEALTH_READY=true
    break
  fi
  sleep 5
done
if [[ "$HEALTH_READY" == true ]]; then
  note "HTTPS health check passed."
else
  warn "HTTPS health check did not pass from this deployment box."
  SKIPPED+=("verify https://$PGH_HOST/healthz from an approved Agent Host")
fi

stage "Store upstream GitHub credential"
say "The PAT is sent only over stdin to the in-pod admin command and is encrypted before database storage."
[[ -n "$(_existing PGH_CREDENTIAL_NAME || true)" ]] || write_env PGH_CREDENTIAL_NAME "operator-github"
ask PGH_CREDENTIAL_NAME "Credential name:"
validate_dns_label "credential name" "$PGH_CREDENTIAL_NAME"
write_env PGH_CREDENTIAL_NAME "$PGH_CREDENTIAL_NAME"
step "Retrieve the approved upstream GitHub PAT from your secret manager."
ask_secret PGH_OPERATOR_PAT "GitHub PAT:"
require_value "GitHub PAT" "$PGH_OPERATOR_PAT"
warn "Using an existing credential name rotates its PAT for all linked capabilities."
confirm "Store or replace credential $PGH_CREDENTIAL_NAME?" || die "stopped before credential mutation"
printf '%s\n' "$PGH_OPERATOR_PAT" |
  kubectl_ns exec -i "deployment/$DEPLOYMENT_NAME" -- \
    pgh-broker credential put --name "$PGH_CREDENTIAL_NAME" --host github.com
unset PGH_OPERATOR_PAT

stage "Issue repository capability"
say "Issue one short-lived token bound to an immutable GitHub repository ID and explicit policy."
ask TARGET_REPOSITORY "Repository as OWNER/NAME:"
[[ "$TARGET_REPOSITORY" =~ ^[A-Za-z0-9][A-Za-z0-9-]*/[A-Za-z0-9._-]+$ ]] ||
  die "repository must be exactly OWNER/NAME"
ask TARGET_REPOSITORY_ID "Immutable GitHub repository ID:"
[[ "$TARGET_REPOSITORY_ID" =~ ^[1-9][0-9]*$ ]] || die "repository ID must be a positive integer"
[[ -n "$(_existing TARGET_DEFAULT_BRANCH || true)" ]] || write_env TARGET_DEFAULT_BRANCH "main"
ask TARGET_DEFAULT_BRANCH "Default branch:"
require_value "default branch" "$TARGET_DEFAULT_BRANCH"
[[ -n "$(_existing TARGET_POLICY || true)" ]] || write_env TARGET_POLICY "developer"
ask TARGET_POLICY "Policy profile:"
require_value "policy profile" "$TARGET_POLICY"
[[ -n "$(_existing TARGET_POLICY_VERSION || true)" ]] || write_env TARGET_POLICY_VERSION "1"
ask TARGET_POLICY_VERSION "Policy version:"
[[ "$TARGET_POLICY_VERSION" =~ ^[1-9][0-9]*$ ]] || die "policy version must be a positive integer"
[[ -n "$(_existing TARGET_GIT_PUSH || true)" ]] || write_env TARGET_GIT_PUSH "non-default"
ask TARGET_GIT_PUSH "Git push tier (none, non-default, all):"
case "$TARGET_GIT_PUSH" in none|non-default|all) ;; *) die "invalid Git push tier" ;; esac
[[ -n "$(_existing TARGET_GIT_TAGS || true)" ]] || write_env TARGET_GIT_TAGS "false"
ask TARGET_GIT_TAGS "Allow Git tag writes (true/false):"
case "$TARGET_GIT_TAGS" in true|false) ;; *) die "Git tag setting must be true or false" ;; esac
ask TARGET_GRANTS "Additional grants, comma-separated (blank for none):"
IFS=',' read -r -a GRANTS <<< "$TARGET_GRANTS"
if [[ -n "$TARGET_GRANTS" ]]; then
  validate_grants "${GRANTS[@]}"
else
  GRANTS=()
fi
[[ -n "$(_existing TARGET_EXPIRES_IN || true)" ]] || write_env TARGET_EXPIRES_IN "8h"
ask TARGET_EXPIRES_IN "Capability lifetime, for example 8h:"
[[ "$TARGET_EXPIRES_IN" =~ ^[1-9][0-9]*(ns|us|µs|ms|s|m|h)$ ]] ||
  die "capability lifetime must be one positive Go duration component, such as 30m or 8h"
write_env TARGET_REPOSITORY "$TARGET_REPOSITORY"
write_env TARGET_REPOSITORY_ID "$TARGET_REPOSITORY_ID"
write_env TARGET_DEFAULT_BRANCH "$TARGET_DEFAULT_BRANCH"
write_env TARGET_POLICY "$TARGET_POLICY"
write_env TARGET_POLICY_VERSION "$TARGET_POLICY_VERSION"
write_env TARGET_GIT_PUSH "$TARGET_GIT_PUSH"
write_env TARGET_GIT_TAGS "$TARGET_GIT_TAGS"
write_env TARGET_GRANTS "$TARGET_GRANTS"
write_env TARGET_EXPIRES_IN "$TARGET_EXPIRES_IN"
ISSUE_COMMAND=(
  pgh-broker capability issue
  --credential "$PGH_CREDENTIAL_NAME"
  --repo "$TARGET_REPOSITORY"
  --repository-id "$TARGET_REPOSITORY_ID"
  --default-branch "$TARGET_DEFAULT_BRANCH"
  --policy "$TARGET_POLICY"
  --policy-version "$TARGET_POLICY_VERSION"
  --git-push "$TARGET_GIT_PUSH"
  --expires-in "$TARGET_EXPIRES_IN"
)
if [[ "$TARGET_GIT_TAGS" == true ]]; then
  ISSUE_COMMAND+=(--git-tags)
fi
for GRANT in "${GRANTS[@]}"; do
  ISSUE_COMMAND+=(--grant "$GRANT")
done
warn "Issuing creates a new bearer token. Its plaintext is shown once and cannot be recovered."
confirm "Issue this capability now?" || die "stopped before capability creation"
CAPABILITY_TOKEN=$(kubectl_ns exec "deployment/$DEPLOYMENT_NAME" -- "${ISSUE_COMMAND[@]}")
[[ "$CAPABILITY_TOKEN" == pgh_pat_* ]] || die "Broker did not return a capability token"
if [[ "$HEALTH_READY" == true ]]; then
  if printf 'url = "https://%s/api/v3/repos/%s"\nheader = "Authorization: Bearer %s"\nfail\nsilent\nshow-error\n' \
      "$PGH_HOST" "$TARGET_REPOSITORY" "$CAPABILITY_TOKEN" | curl --config - >/dev/null; then
    note "Capability successfully read its bound repository through the Broker."
  else
    warn "The capability verification request failed. Revoke it before retrying deployment changes."
    SKIPPED+=("verify or revoke the newly issued capability")
  fi
fi
printf '\n  %sStore these values in the Agent Host secret manager now.%s\n' "$BOLD" "$RESET"
printf '  PGH_HOST=%s\n' "$PGH_HOST"
printf '  PGH_TOKEN=%s\n\n' "$CAPABILITY_TOKEN"
pause "Press Enter only after the capability token has been stored. It will be cleared from this process."
unset CAPABILITY_TOKEN

finish
